transpiler swc로 변경
telbby/telbby-frontend pull request #39
Opened 2021-12-01 07:56 UTC by jiyong1

## 개요 

기존 `babel` 로 설정되어있던 transpiler를 `swc` 로 변경하였습니다.

## 이슈 번호

- closes #38 

## 변경사항 

- `babel` 과 관련된 plugin 및 로더 등의 패키지를 삭제하였습니다.
- `swc` 를 사용하기 위한 패키지를 다운로드 하였습니다.
- `webpack` 에 alias를 추가하였습니다.
- `jest` 설정 파일의 transpiler를 `swc` 로 사용하기 위해 `jest.config.js` 파일을 수정하였습니다.

## 특이사항

- 아직 완벽한 transpiler가 아닐 수 있어서 개발 도중 오류가 발생할 수 있습니다. 발생한다면 말씀해주세요 !
  - 일단 현재 개발된 컴포넌트 들과 테스트 코드들은 빌드가 잘 되는 것을 확인하였습니다.

2021-12-02 05:17 UTC, jonghopark95 approved these changes
수고 많으셨습니다!! 테스트 속도 완전 빨라지네요 대박

2021-12-02 05:17 UTC, jonghopark95 commented on config/webpack/webpack.common.js
>              loader: 'ts-loader',
확실하진 않지만 `swc-loader` 를 사용하면 `ts-loader` 를 지워도 되지 않을까요 ??

2021-12-02 05:18 UTC, jonghopark95 commented on package.json
>      "ts-jest": "^27.0.7",
`ts-ject` 도 지워도 될 것 같습니다

2021-12-02 05:56 UTC, jiyong1 commented on config/.swcrc
> +        "pragmaFrag": "React.Fragment",
아직 안익숙해서 어떤 속성이 있나 좀 보면서 하다보니 default인 것들에 대해 신경을 안썼어요..
지우는게 나을까요 ?

2021-12-02 05:56 UTC, jiyong1 commented on config/jest.config.js
> +    '^.+\\.(j|t)sx?$': ['@swc/jest', { ...swcConfig }],
맞습니다 !!!

2021-12-02 05:56 UTC, jiyong1 commented on config/webpack/webpack.common.js
>              loader: 'ts-loader',
죄송하지만 ts-loader의 역할이 정확하게 어떤건가요??

2021-12-02 05:57 UTC, jiyong1 commented on package.json
>      "ts-jest": "^27.0.7",
넵 수정하겠습니다 ~~~

2021-12-02 07:48 UTC, jonghopark95 commented on config/.swcrc
> +        "pragmaFrag": "React.Fragment",
저는 특별한 이유가 없으면 지우는게 좋다고 생각하는데... 움 이건 다른 분들 의견도 반영해야 될것 같습니다!!

2021-12-02 08:28 UTC, jonghopark95 commented on config/webpack/webpack.common.js
>              loader: 'ts-loader',
webpack 에서 loader 의 역할은 빌드를 원하는 코드에 추가적인 기능을 넣어주는 것이고, 
탑재된 loader 를 역순으로 transpiling, polyfill, compiling 해주는 것으로 알고 있습니다.

지용님이 개선하기 전 코드는 `ts-loader` 에서 TS -> JS, 
`babel-loader` 에서 작성된 JS 중 ecmascript 상위 메서드 compiling, 하위 브라우저 버전 polyfill 등의 작업을 한것으로 알고 있습니다. (제가 한 설정이 아니라 확실하지 않음)

작성하신 `.swcrc` 를 보시면 `parser` 가 있는데, 이 부분에서 `typescript` 를 파싱하는 부분이 있습니다.
따라서 `ts-loader` 가 하는 일을 충분히 할 수 있으니 이를 지워도 되지 않을까? 라는 생각에 리뷰를 남겼습니다.

실제로 지워보니 컴파일은 되는데, `emotion` 관련해 문제가 생겼습니다.
<img width="671" alt="스크린샷 2021-12-02 오후 5 18 27" src="https://user-images.githubusercontent.com/19240202/144383881-dad6cda9-36b4-4885-b772-f7aa5356354c.png">

`css 함수에서 반환해준 stringify object`를 `css prop` 에서 사용할수 없다... 이런 내용인 것 같습니다.
추측컨데, `.swcrc` 에서 사용하신 `importSource` 에서 `@emotion/react` 가 잘 동작하지 않는 것 같습니다.
이전에 되었던 이유는 `ts-loader` 의 `jsxImportSource` 에서 동작을 했기 때문이었던 것 같습니다.

실제로 `.swcrc 의 importSource` 를 지워도 잘 동작합니다.

2021-12-02 08:32 UTC, jonghopark95 commented on config/webpack/webpack.common.js
>              loader: 'ts-loader',
너무 글이 길어진 것 같아 정리하자면, 제 생각은 다음과 같습니다.

1. webpack 에서 `ts-loader` 를 사용할 거면 `parser` 부분을 다 지워줘도 될것 같습니다. 
이미 `ts-loader` 에서 파싱을 해주기 때문입니다.

2. 더불어 `importSource` 도 지워도 될 것 같습니다.

3. `.swcrc` 에서 `@emotion/react` 가 잘 동작하도록 수정해주면 `ts-loader` 를 지워도 될 것 같습니다. 
다만 관련 레퍼런스가 안나와서 이에 대해선 잘 모르겠네요

위의 `default` 속성으로 지정된 것들까지 지우면, `.swcrc` 가 꽤 깔끔해집니다.

```bash
{
  "jsc": {
    "transform": {
      "react": {
        "runtime": "automatic",
        "throwIfNamespace": true
      }
    }
  },
  "env": {
    "targets": ">= 1%, not dead",
    "mode": "usage",
    "coreJs": 3
  },
  "minify": true
}
```

해당 설정 파일로 잘 돌아갑니다.

다만 위 발언들이 제 추측이 무던히 섞여있어서 검증이 필요할 것 같습니다... 확인해보시고 리뷰 달아주셔요 !!

2021-12-02 09:54 UTC, hseoy approved these changes
SWC는 처음이라 아직 정확하게 파악이 안되서....

설정 같은 경우에는 사용해보면서 개선해 나가면 되지 않을까.... 하는 마음에서 approve합니당.

2021-12-02 09:54 UTC, hseoy commented on config/webpack/webpack.common.js
>              loader: 'ts-loader',
> 지용님이 개선하기 전 코드는 ts-loader 에서 TS -> JS,
babel-loader 에서 작성된 JS 중 ecmascript 상위 메서드 compiling, 하위 브라우저 버전 polyfill 등의 작업을 한것으로 알고 있습니다. 

그런 목적으로 설정해줬었습니다. 근데 typescript 같은 경우에는 `babel-loader& @babel/preset-typescript`를 사용할 수도 있지만 이 경우에는 타입 체킹을 해주지 않습니다. 그래서 타입 체킹을 위해 ts-loader를 선택했었습니다.

> .swcrc 에서 @emotion/react 가 잘 동작하도록 수정해주면 ts-loader 를 지워도 될 것 같습니다.

https://github.com/swc-project/swc/issues/838#issuecomment-967201316 Comment를 확인해보면 `@emotion/react`가 잘 동작하는 것 같은 데 저희 같은 경우엔 잘 동작하지 않네요,,,,  해결해보려고 쫌 찾아봤는 데 해결법을 모르겠어서,,,, 당장은 ts-loader를 사용하는 게 맞는 것 같습니다!

> 1. webpack 에서 ts-loader 를 사용할 거면 parser 부분을 다 지워줘도 될것 같습니다.
이미 ts-loader 에서 파싱을 해주기 때문입니다.
> 2. 더불어 importSource 도 지워도 될 것 같습니다.

ts-loader를 사용하게 되면 tsconfig.json를 기반으로 ts를 js로 트랜스파일링하기 때문에 `parser`와 `importSource`(tsconfig.json에 명시되어 있습니다)는 불필요한 속성인 것 같아보이는 데 swc에 대해서 아직 명확하게 이해하지 못한 상태라 ... 확신은 못하겠습니다.

2021-12-02 10:36 UTC, hseoy requested changes
다시 봤는 데 바로 main branch로 merge되도록 되어 있네요.

dev 브랜치로 바꿔줘야 할 것 같습니당.

2021-12-02 15:38 UTC, jiyong1 commented on config/.swcrc
> +        "pragmaFrag": "React.Fragment",
넵 수정하겠습니다 !

2021-12-02 15:40 UTC, jiyong1 commented on config/webpack/webpack.common.js
>              loader: 'ts-loader',
그렇다면
1. 현재 단계에서는 일단 ts loader를 사용한다.
2. 그렇기에 parser 속성은 굳이 필요 없다.
3. default 값은 굳이 적지 말자

이렇게 수정하면 되는거죠 ?!

2021-12-02 15:48 UTC, jonghopark95 commented on config/webpack/webpack.common.js
>              loader: 'ts-loader',
지용님이 동의하신다면 그렇게 수정하면 될것 같습니다!!

2021-12-02 15:49 UTC, jiyong1 commented
> 다시 봤는 데 바로 main branch로 merge되도록 되어 있네요.
> 
> dev 브랜치로 바꿔줘야 할 것 같습니당.

아이구.. 죄송합니다 수정했습니다 !!

2021-12-02 23:17 UTC, hseoy approved these changes

2021-12-05 13:38 UTC, Seogeurim approved these changes
테스트 잘 되는 것 확인했습니다!
관련 토의는 PR 리뷰 되어있는 것 보면서 이해했어요!!
저도 swc는 처음인데, 이번 기회에 써볼 수 있어서 좋은 것 같습니다 👍🏻👍🏻👍🏻

2021-12-05 13:39 UTC, merged