Shell Component 계층 수정
telbby/telbby-frontend pull request #44
Opened 2021-12-02 15:22 UTC by jonghopark95

## 개요 

Shell Component 계층 수정

## 이슈 번호

- closes #43 

## 변경사항 
- `ShellLine` 컴포넌트 `Shell` 내부로 이동
- `Shell` 컴포넌트 `common` 폴더로 이동

## 특이사항 
- `ShellLine` 컴포넌트가 오직 `Shell` 에서만 쓰이기 때문에 `Shell` 안으로 넣어주는게 어떨까 생각했습니다.
   다만, 컴포넌트 내부에 컴포넌트가 있는 형태라 맞는 구조인지 모르겠습니다... 리뷰 부탁드립니다.
- `Shell` 컴포넌트는 여타 `Jumbotron` 컴포넌트처럼 페이지에서 사용할 수 있는 컴포넌트라 생각하고 `common` 내부로 이동시켰습니다. 
  여러분들의 생각은 어떠신가요??

2021-12-02 15:42 UTC, jiyong1 requested changes
main 브랜치로 머지되게 돼있습니다 ! 수정부탁드립니다 ~

2021-12-02 15:47 UTC, jonghopark95 commented
> main 브랜치로 머지되게 돼있습니다 ! 수정부탁드립니다 ~

이 실수 너무 자주하네요 ㅠㅠ 감사합니다!!

2021-12-03 00:27 UTC, hseoy reviewed
> ShellLine 컴포넌트가 오직 Shell 에서만 쓰이기 때문에 Shell 안으로 넣어주는게 어떨까

컴포넌트 레벨에서 특정 컴포넌트 내에서만 사용될 경우 해당 컴포넌트 하위로 넣어준다라는 규칙을 적용하게 되면 현재의 가능성만 보고 그 컴포넌트의 재사용을 의도적으로 막는 행위가 아닐까 싶습니다. 

지금은 Shell 컴포넌트만 있지만 ShellLine 컴포넌트를 필요로 하는 다른 파생 Shell 컴포넌트를 구현할 일이 있을 수도 있고 없을 수도 있는데 `굳이 사용범위를 한정시켜야 할까? 컴포넌트의 존재 목적은 재사용이 아닌가?`하는 생각이 듭니다. 

전 그래서 기존에 제안드렸던 방식대로 Shell, ShellLine 컴포넌트를 별도의 디렉토리(`ex - shell`)로 묶는 것이 좋아보입니다.

2021-12-03 04:25 UTC, jonghopark95 commented
> > ShellLine 컴포넌트가 오직 Shell 에서만 쓰이기 때문에 Shell 안으로 넣어주는게 어떨까
> 
> 컴포넌트 레벨에서 특정 컴포넌트 내에서만 사용될 경우 해당 컴포넌트 하위로 넣어준다라는 규칙을 적용하게 되면 현재의 가능성만 보고 그 컴포넌트의 재사용을 의도적으로 막는 행위가 아닐까 싶습니다.
> 
> 지금은 Shell 컴포넌트만 있지만 ShellLine 컴포넌트를 필요로 하는 다른 파생 Shell 컴포넌트를 구현할 일이 있을 수도 있고 없을 수도 있는데 `굳이 사용범위를 한정시켜야 할까? 컴포넌트의 존재 목적은 재사용이 아닌가?`하는 생각이 듭니다.
> 
> 전 그래서 기존에 제안드렸던 방식대로 Shell, ShellLine 컴포넌트를 별도의 디렉토리(`ex - shell`)로 묶는 것이 좋아보입니다.

아하... 좋습니다 수정했습니다!!

[관련 커밋](https://github.com/telbby/telbby-frontend/pull/44/commits/37ef8d47b3e80e33f3f8ac213721b839cd2166ec)

2021-12-05 14:05 UTC, Seogeurim approved these changes
아하 요 PR은 계층 수정만 있는 PR이군요!! ㅎㅎㅎ
볼 코드가 많이 없어 수월했습니다!

컴포넌트 계층 관련해서나, 컴포넌트 분리 관련해서는 팀원들 각각 생각이 달라서 처음부처 맞추기도 어렵고 결국은 나중에 리팩토링을 하면서 맞추게 되더라구요!!! 그래서 우선은 요렇게 분리해놓고 나중에 얘기해보는 것도 좋을 것 같아요~~!🤗

2021-12-06 23:27 UTC, hseoy approved these changes

2021-12-07 01:10 UTC, merged