서비스 수정 페이지 마크업
telbby/telbby-frontend pull request #57
Opened 2021-12-15 16:43 UTC by Seogeurim

## 개요 

서비스 수정 페이지 마크업입니다.
채팅 페이지와 같이 올리려 했는데, PR 리뷰할 때 혼돈이 있을까하여 따로 올립니다.
채팅 마크업은 내일 올리겠습니다!

## 이슈 번호

- closes #51 

## 변경사항 

- 서비스 수정 페이지 생성
- ServiceEditForm 컴포넌트 작업

![image](https://user-images.githubusercontent.com/22045163/146227846-006b3207-706f-4b80-abae-c6bca1fbf1fa.png)

## 특이사항 

- /service-edit 페이지로 들어가면 됩니다!
- 크게 이슈되는 작업이 없을 것입니다!! 빠진 기능 있나 한 번 봐주세요~

2021-12-18 02:03 UTC, Seogeurim commented
아맞다 테스트코드!!! 를 깜빡했네요... 작업기간이 늦어지면 다른 이슈로 파서 진행하겠습니다 :)

2021-12-19 06:46 UTC, jonghopark95 approved these changes
수고 많으셨습니다~~

2021-12-19 06:46 UTC, jonghopark95 commented on src/components/service/ServiceEditForm/index.tsx
> +          <img src={image.preview} alt="service profile" />
오홍 이미지 클릭하면 사진 변경할 수 있군요!!

2021-12-19 06:46 UTC, jonghopark95 commented on src/components/service/ServiceEditForm/index.tsx
> +            <span />
여기랑 153 lien 에 `<span />` 이 들어가는 이유는 어떤걸까요??

2021-12-19 06:46 UTC, jonghopark95 commented on src/components/service/ServiceEditForm/style.ts
> +    height: fit-content;
오... 여기에 `fit-content` 가 들어가야 할 이유가 있을까용...? 궁금궁금

2021-12-19 06:46 UTC, jonghopark95 requested changes
앗 지금 보니 App.tsx 에 conflict 나네용 수정되면 approve 로 돌리겠습니다 😅

2021-12-20 02:04 UTC, hseoy approved these changes
값이 수정되었을 때만 SAVE 버튼이 활성화 되고 수정이 되지 않았을 때는 disable되어야 하지 않나 싶습니다. figma 상에 memo를 남겨놨었는 데 혹시 의도적으로 제외한 기능이신지요?

추가적으로 추후에 서비스 설정 페이지는 상단 navbar 대신 sidebar를 사용하도록 수정해야 할 필요성이 있을 것 같네용

2021-12-20 02:04 UTC, hseoy commented on src/components/service/ServiceEditForm/index.tsx
> +          <h1>{name}</h1>
요기에 h1 태그를 사용했는 데 문서의 제일 큰 제목에 해당하는 것은 Sidebar의 Settings 아닐까요? h1 태그는 문서에서 하나만 있어야 한다고 알고 있어서 comment 남겨봅니다.

![image](https://user-images.githubusercontent.com/75124422/146701531-9da5e86e-b6ef-42f7-a1a5-38902c15b61d.png)

2021-12-22 12:29 UTC, jonghopark95 approved these changes

2021-12-23 06:06 UTC, jiyong1 approved these changes
고생하셨습니다.. 제가 채팅 컴포넌트 작성이 좀 늦네요.. 금방 마무리하겠습니다 !!

2021-12-23 06:06 UTC, jiyong1 commented on src/components/service/ServiceEditForm/style.ts
> +  img {
가끔 궁금한 내용이긴 했는데..

`styled-components` 나 `emotion`이 nesting을 지원하긴 하지만 어느정도 선까지 nesting을 하고, 또 어느정도에서는 따로 선언해줘야할지 항상 궁금합니다.. 혹시 명쾌한 답변이 있을까요..?

2021-12-26 09:48 UTC, Seogeurim commented on src/components/service/ServiceEditForm/index.tsx
> +            <span />
아 ! radio button을 커스터마이징해주기 위해 넣어주고 있습니다! 
https://www.w3schools.com/howto/howto_css_custom_checkbox.asp

2021-12-26 09:54 UTC, Seogeurim commented on src/components/service/ServiceEditForm/style.ts
> +    height: fit-content;
아 이 부분을 안 넣어주니 버튼이 쪼그라들어서 넣어줬던 것 같아요!! 
그런데 지금 다시 실행해보고 확인해보니 있는거랑 없는게 별 차이가 없네요 ...? 무슨 일이지 ㅋㅋㅋㅋㅋ

2021-12-26 09:55 UTC, Seogeurim commented on src/components/service/ServiceEditForm/index.tsx
> +          />
오 좋습니다!!!

2021-12-26 09:57 UTC, Seogeurim commented on src/components/service/ServiceEditForm/index.tsx
> +          <h1>{name}</h1>
아하 !! 네브바 마크업을 고려하지 못했네용 좋습니다 수정하겠습니당

2021-12-26 09:58 UTC, Seogeurim commented on src/components/service/ServiceEditForm/index.tsx
> +  });
오호 제가 빠뜨렸네용 추가하겠습니다!!

2021-12-26 10:00 UTC, Seogeurim commented on src/components/service/ServiceEditForm/style.ts
> +  img {
초기에 컨벤션 정할 때는 일단 
묶을 수 있는 스타일은 묶고, 그 아래에 선택자로 스타일링 가능한 부분은 nesting으로 표현하자고 했던 것 같아요!!
명쾌한 답변이라기보다는 컨벤션이지 않을까 하고 이렇게 정했던 것 같네요!

2021-12-26 10:00 UTC, Seogeurim commented
@hseoy 
> 한 가지 기능적인 부분에서 값이 수정되었을 때만 SAVE 버튼이 활성화 되고 수정이 되지 않았을 때는 disable되어야 하지 않나 싶습니다. figma 상에 memo를 남겨놨었는 데 혹시 의도적으로 제외한 기능이신지요?

메모를 확인하지 못했네요! 이 부분 수정해서 올릴게요!

2021-12-26 10:44 UTC, Seogeurim commented
- PR 리뷰 내용 수정 완료
- API 연동 시 테스트 코드 추가 예정

2021-12-26 10:46 UTC, merged